services:
  postgis:
    image: postgis/postgis:16-3.4
    restart: always
    environment:
      POSTGRES_DB: dearth
      POSTGRES_USER: dearth
      POSTGRES_PASSWORD: dearthdbpassword
    ports:
      - "5432:5432"

  ows:
    image: local:ows
    # build:
    #   context: ows
    #   dockerfile: Dockerfile
    volumes:
      - ./ows/ows_config:/env/config/ows_config
    environment:
      - DB_HOSTNAME=postgis
      - DB_USERNAME=dearth
      - DB_PASSWORD=dearthdbpassword
      - DB_DATABASE=dearth
      - ODC_DEFAULT_INDEX_DRIVER=postgis
      - PYTHONPATH=/env/config
      - WMS_CONFIG_PATH=/env/config/ows_config/pacific_ows.py
      - DATACUBE_OWS_CFG=ows_config.pacific_ows.ows_cfg
    ports:
      - "8000:8000"
