services:
  postgis:
    image: postgis/postgis:16-3.4
    restart: always
    environment:
      POSTGRES_USER: pacific
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: pacific
    ports:
      - "5432:5432"
  ows:
    build:
      context: ows
      dockerfile: Dockerfile
    volumes:
      - ./ows/ows_config:/env/config/ows_config
    environment:
      - DB_HOSTNAME=postgis
      - DB_USERNAME=pacific
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DATABASE=pacific
      - PYTHONPATH=/env/config
      - WMS_CONFIG_PATH=/env/config/ows_config/pacific_ows.py
      - DATACUBE_OWS_CFG=ows_config.pacific_ows.ows_cfg
    ports:
      - "8000:8000"
