name: Build and Push Docker Images

env:
  REGISTRY: ghcr.io
  IMAGE_OWS: digitalearthpacific/datacube-ows
  IMAGE_ODC: digitalearthpacific/datacube

on:
  pull_request:
  push:
    branches:
      - main
  release:
    types:
      - created

jobs:
  test-ows:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ows
          push: false
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_OWS }}:test
          cache-from: type=gha
          cache-to: type=gha,mode=max

  push-ows:
    permissions: write-all
    if: github.ref == 'refs/heads/main' || github.event_name == 'release'
    needs: test-ows
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
        
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get version number for tagging the image
        id: get_version
        run: |
          git fetch --all --tags
          echo "VERSION=$(git describe --tags)" >> $GITHUB_OUTPUT

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ows
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_OWS }}:${{ steps.get_version.outputs.VERSION }},${{ env.REGISTRY }}/${{ env.IMAGE_OWS }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

  test-datacube:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: false
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_ODC }}:test
          cache-from: type=gha
          cache-to: type=gha,mode=max

  push-datacube:
    permissions: write-all
    if: github.ref == 'refs/heads/main' || github.event_name == 'release'
    needs: test-datacube
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
        
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get version number for tagging the image
        id: get_version
        run: |
          git fetch --all --tags
          echo "VERSION=$(git describe --tags)" >> $GITHUB_OUTPUT

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_ODC }}:${{ steps.get_version.outputs.VERSION }},${{ env.REGISTRY }}/${{ env.IMAGE_ODC }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
